---
title: "Iteration and List Columns"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

## Lists


```{r}
l <-  
  list(
    vec_numeric = 5:8,
    vec_logical = c(TRUE,FALSE),
    summary = summary(rnorm(1000,5,3))
     )

l[[3]]

l[["summary"]]

l$summary
```


## list of normals
```{r}
list_norms <-  
  list(
    a = rnorm(50, 2, 1),
    b = rnorm(50, 5, 3),
    c = rnorm(50, 10, .2),
    d = rnorm(50, -3, 1)
  )

is.list(list_norms)
```

## define the function
```{r}
mean_and_sd = function(x){
  if(!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if(length(x)<3){
    stop("x should have at least 3 numbers")
  }
  mean_x <-  mean(x)
  sd_x <-  sd(x)
  
  output_df <- 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  
  return(output_df)
}

mean_and_sd(list_norms[[1]])
```

## for loop
let's use a for loop to iterate over my list of normals
```{r}
output <- vector("list",length = 4)

output[[1]] = mean_and_sd(list_norms[[1]])

for (i in 1:4){
  output[[i]] = mean_and_sd(list_norms[[i]])
}

```

let's use map instead

```{r}
output_meansd <- map(list_norms,mean_and_sd)
output_summart <- map(list_norms,summary)

output_median <- map_dbl(list_norms,median)
```

## List Columns!!!1
```{r}
listcol_df <- 
  tibble(
    name = c("a","b","c","d"),
    norms = list_norms
  )

listcol_df %>% 
  filter( name =="a")

listcol_df %>% pull(name)
listcol_df %>%  pull(norms)

mean_and_sd(listcol_df$norms[[1]])

listcol_df %>% 
  mutate(summary <- map(listcol_df$norms,mean_and_sd))
```

## Nested data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

Nest data within location
```{r}
#nest and unest
weather_nest <- nest(weather_df,data = date:tmin)
unnest

weather_nest %>% 
  filter(name == "CentralPark_NY")

## regression
weather_lm = function(df){
  lm(tmax ~ tmin,data = df)
}

lm(tmax ~ tmin, data = weather_nest$data[[3]])
weather_lm(weather_nest$data[[3]])

map(weather_nest$data,weather_lm)

weather_nest %>% 
  mutate(lm_results = map(data,weather_lm))
```

```{r，eval=FALSE}
read_page_reviews <- function(url) {
  
  html = read_html(url)
  
  review_titles = 
    html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()
  
  review_stars = 
    html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()
  
  review_text = 
    html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim()
  
reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
  )
  return(reviews)
}

url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
vec_urls = str_c(url_base,1:5)

map(vec_urls,read_page_reviews )

napoleon_df <- 
  tibble(
    urls = vec_urls
  )

napoleon_df %>% 
  mutate(reviews =map(urls,read_page_reviews )) %>% 
  select(reviews) %>% 
  unnest(map(vec_urls,read_page_reviews ))
```

